[package]
name = "advent_solutions"
version = "0.1.0"
authors = ["alvaro-cuesta <alvaro-cuesta@GitHub>"]

[dependencies]
reqwest = "0.8.2"
itertools = "0.7.4"
threadpool = "1.7.1"

[dependencies.nom]
version = "^3.2"
features = ["nightly"]
